## Web Scrape by Using API
### Website: https://www.flightera.net/en/airport/Bedford/KBED/departure/2023-06-01%20%2000_00?

In [2]:
import pandas as pd
import requests

In [16]:
url = "https://flightera-flight-data.p.rapidapi.com/airport/flights"

querystring = {"direction":"departure","time":"2023-06-29T13:05:00Z","ident":"KBED"}

headers = {
	"X-RapidAPI-Key": "93a1c2e6bemsh1c89f0bd4d8f7a1p1c4068jsn985518990be9",
	"X-RapidAPI-Host": "flightera-flight-data.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

# print(response.json())
data1 = response.json()
# Create a dataframe from the JSON data
df1 = pd.DataFrame(data1)
# Print the dataframe
df1[['flnr', 'date']] = df1['flights'].apply(lambda x: pd.Series([x['flnr'], x['date']]))
df1

,flights,next_time,flnr,date
0,"{'flnr': 'CNS794', 'date': '2023-06-29T00:00:0...",2023-07-03T21:00:00Z,CNS794,2023-06-29T00:00:00Z
1,"{'flnr': 'CNS95', 'date': '2023-06-29T00:00:00...",2023-07-03T21:00:00Z,CNS95,2023-06-29T00:00:00Z
2,"{'flnr': 'JAS918', 'date': '2023-06-29T00:00:0...",2023-07-03T21:00:00Z,JAS918,2023-06-29T00:00:00Z
3,"{'flnr': 'LAK296', 'date': '2023-06-29T00:00:0...",2023-07-03T21:00:00Z,LAK296,2023-06-29T00:00:00Z
4,"{'flnr': 'CNS130', 'date': '2023-06-29T00:00:0...",2023-07-03T21:00:00Z,CNS130,2023-06-29T00:00:00Z
...,...,...,...,...
69,"{'flnr': 'CNS930', 'date': '2023-07-02T00:00:0...",2023-07-03T21:00:00Z,CNS930,2023-07-02T00:00:00Z
70,"{'flnr': 'CNS1776', 'date': '2023-07-02T00:00:...",2023-07-03T21:00:00Z,CNS1776,2023-07-02T00:00:00Z
71,"{'flnr': 'DL8878', 'date': '2023-07-02T00:00:0...",2023-07-03T21:00:00Z,DL8878,2023-07-02T00:00:00Z
72,"{'flnr': 'LXJ417', 'date': '2023-07-03T00:00:0...",2023-07-03T21:00:00Z,LXJ417,2023-07-03T00:00:00Z
73,"{'flnr': 'JAS82', 'date': '2023-07-03T00:00:00...",2023-07-03T21:00:00Z,JAS82,2023-07-03T00:00:00Z

In [17]:
# Define the API endpoint and headers
url = "https://flightera-flight-data.p.rapidapi.com/flight/info"
headers = {
    "X-RapidAPI-Key": "93a1c2e6bemsh1c89f0bd4d8f7a1p1c4068jsn985518990be9",
    "X-RapidAPI-Host": "flightera-flight-data.p.rapidapi.com"
}

# Create an empty dataframe to store the API responses
df_fina = pd.DataFrame()

# Iterate over the rows of df1 and make API calls
for index, row in df1.iterrows():
    # Get the flight details from df1
    flnr = row['flnr']
    date = row['date']
    
    # Set the querystring parameters
    querystring = {"flnr": flnr, "date": date}
    
    # Make the API request
    response = requests.get(url, headers=headers, params=querystring)
    
    # Check if the API request was successful
    if response.status_code == 200:
        # Get the JSON data from the API response
        data = response.json()
        
        # Create a dataframe from the JSON data
        df_temp = pd.DataFrame(data)
        
        # Concatenate the dataframe to the final dataframe
        df_fina = pd.concat([df_fina, df_temp], ignore_index=True)
    else:
        # Handle the case when the API request fails
        print(f"API request for flight {flnr} on {date} failed")

# Print the resulting DataFrame
df_fina

,flnr,date,scheduled_departure_utc,actual_departure_utc,scheduled_departure_local,actual_departure_local,actual_departure_is_estimated,departure_icao,departure_iata,departure_name,...,actual_arrival_local,actual_arrival_is_estimated,status,reg,model,family,departure_gate,arrival_terminal,arrival_gate,departure_terminal
0,CNS794,2023-06-29T00:00:00Z,2023-06-29T18:06:00Z,2023-06-29T18:51:22Z,2023-06-29T14:06:00-04:00,2023-06-29T14:51:22-04:00,False,KACK,ACK,Nantucket Memorial Airport,...,2023-06-29T16:07:16-04:00,False,landed,N954AF,PC12,PC-12,NaN,NaN,NaN,NaN
1,CNS794,2023-06-29T00:00:00Z,2023-06-29T15:37:00Z,2023-06-29T15:22:40Z,2023-06-29T11:37:00-04:00,2023-06-29T11:22:40-04:00,False,KAUG,AUG,Augusta State Airport,...,2023-06-29T11:59:21-04:00,False,landed,N954AF,PC12,PC-12,NaN,NaN,NaN,NaN
2,CNS794,2023-06-29T00:00:00Z,2023-06-29T20:30:00Z,2023-06-29T22:38:18Z,2023-06-29T16:30:00-04:00,2023-06-29T18:38:18-04:00,False,,PCT,Princeton Airport,...,None,False,diverted,N954AF,PC12,PC-12,NaN,NaN,NaN,NaN
3,CNS794,2023-06-29T00:00:00Z,2023-06-29T12:40:00Z,2023-06-29T13:00:32Z,2023-06-29T08:40:00-04:00,2023-06-29T09:00:32-04:00,False,KPSM,PSM,Portsmouth International Airport,...,2023-06-29T09:21:11-04:00,False,landed,N954AF,PC12,PC-12,NaN,NaN,NaN,NaN
4,CNS794,2023-06-29T00:00:00Z,2023-06-29T17:00:00Z,2023-06-29T17:11:31Z,2023-06-29T13:00:00-04:00,2023-06-29T13:11:31-04:00,False,KBVY,BVY,Beverly Municipal Airport,...,2023-06-29T13:47:42-04:00,False,landed,N954AF,PC12,PC-12,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,DL8878,2023-07-02T00:00:00Z,2023-07-02T17:25:00Z,2023-07-02T17:28:26Z,2023-07-02T13:25:00-04:00,2023-07-02T13:28:26-04:00,False,KJFK,JFK,John F. Kennedy International Airport,...,2023-07-02T14:32:22-04:00,False,landed,N669DN,B752,B757,B25,NaN,NaN,4
191,LXJ417,2023-07-03T00:00:00Z,2023-07-03T11:12:00Z,2023-07-03T12:40:34Z,2023-07-03T07:12:00-04:00,2023-07-03T08:40:34-04:00,False,KFOK,FOK,Westhampton Beach Francis S Gabresk Airport,...,2023-07-03T09:18:31-04:00,False,landed,N417FX,NaN,NaN,NaN,NaN,NaN,NaN
192,LXJ417,2023-07-03T00:00:00Z,2023-07-03T13:30:00Z,2023-07-03T13:43:21Z,2023-07-03T09:30:00-04:00,2023-07-03T09:43:21-04:00,True,KBED,BED,Bedford Hanscom Field,...,None,False,live,N417FX,NaN,NaN,NaN,NaN,NaN,NaN
193,JAS82,2023-07-03T00:00:00Z,2023-07-03T21:00:00Z,2023-07-03T21:03:21Z,2023-07-03T17:00:00-04:00,2023-07-03T17:03:21-04:00,True,KBED,BED,Bedford Hanscom Field,...,None,False,sched,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,JAS82,2023-07-03T00:00:00Z,2023-07-03T23:00:00Z,2023-07-03T23:00:37Z,2023-07-03T19:00:00-04:00,2023-07-03T19:00:37-04:00,True,KHYA,HYA,Hyannis Barnstable Municipal Airport,...,None,False,sched,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_final = pd.read_csv('/Users/leowu/Desktop/Intern--IPS/Hanscom/Departure_KBED.csv')

In [19]:
df_fina1 = pd.concat([df_final,df_fina])
df_fina1.shape

(8724, 29)

In [20]:
fina3 = df_fina1[df_fina1.departure_icao=='KBED']
fina4 = fina3.drop_duplicates()
fina5 = fina4.reset_index().drop(columns='index')
fina5.shape

(8603, 29)

In [21]:
fina5['date'] = pd.to_datetime(fina5['date'])
fina6 = fina5[fina5.date < '2023-07-01']
fina6.shape

(8567, 29)

In [22]:
fina6.to_csv('Departure_KBED.csv')